{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-umbrella.fullname" . }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "api-umbrella.labels" . | nindent 4 }}
{{- end }}