{{- if .Values.route.enabled -}}
{{- $fullName := include "bae-activation-service.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "bae-activation-service.fullname" . }}
  labels:
    {{ include "bae-activation-service.labels" . | nindent 4 }}
  {{- if .Values.route.annotations }}
  annotations:
    {{- with .Values.route.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  host: {{ .Values.route.host}}
  to:
    kind: Service
    name: {{ $fullName }}
  {{- if .Values.route.tls }}
  tls:
  {{- with .Values.route.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
