{{- if not .Values.database.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "til.fullname" . }}
  labels:
    {{ include "til.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | quote }}
{{- end }}