{{- if .Values.bizEcosystemChargingBackend.enabled -}}
{{- if not .Values.bizEcosystemChargingBackend.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bizEcosystemChargingBackend.fullname" . }}
  labels:
    {{ include "bizEcosystemChargingBackend.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.bizEcosystemChargingBackend.db.password | b64enc }}
  {{- if .Values.bizEcosystemChargingBackend.email.smtp }}
  {{- if .Values.bizEcosystemChargingBackend.email.smtp.password }}
  smtpPassword: {{ .Values.bizEcosystemChargingBackend.email.smtp.password | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.bizEcosystemChargingBackend.plugins.enabled }}
  {{- if .Values.bizEcosystemChargingBackend.plugins.idmPassword }}
  pluginsIdmPassword: {{ .Values.bizEcosystemChargingBackend.plugins.idmPassword | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.bizEcosystemChargingBackend.paypal }}
  {{- if .Values.bizEcosystemChargingBackend.paypal.clientSecret }}
  paypalClientSecret: {{ .Values.bizEcosystemChargingBackend.paypal.clientSecret | b64enc }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
{{ if .Values.bizEcosystemChargingBackend.token.enabled -}}
{{- if not .Values.bizEcosystemChargingBackend.existingCertSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "bizEcosystemChargingBackend.fullname" . }}-certs
  labels:
    {{- include "bizEcosystemChargingBackend.labels" . | nindent 4 }}
data:
  key.pem: |-
    {{ .Values.bizEcosystemChargingBackend.token.key | b64enc | nindent 4 }}
  cert.pem: |-
    {{ .Values.bizEcosystemChargingBackend.token.cert | b64enc | nindent 4 }}

{{- end }}
{{- end }}
