{{- if and .Values.bizEcosystemChargingBackend.enabled .Values.bizEcosystemChargingBackend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bizEcosystemChargingBackend.serviceAccountName" . }}
{{- if .Values.bizEcosystemChargingBackend.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.bizEcosystemChargingBackend.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "bizEcosystemChargingBackend.labels" . | nindent 4 }}
{{- end }}
