apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vcverifier.fullname" . }}
  labels:
    {{- include "vcverifier.labels" . | nindent 4 }}
data:
  server.yaml: |-
    server:
      {{- with .Values.deployment.server }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

    m2m:
      {{- with .Values.deployment.m2m }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      
    logging:
      {{- with .Values.deployment.logging }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

    verifier:
      {{- with .Values.deployment.server }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    
    configRepo:
      {{- with .Values.deployment.configRepo }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
