apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keyrock.fullname" . }}
  labels:
    {{ include "keyrock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
  {{- with .Values.deployment.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keyrock.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "keyrock.labels" . | nindent 8 }}
        {{- with .Values.deployment.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.deployment.additionalAnnotations -}}
      annotations:
        {{- with .Values.deployment.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec: 
      serviceAccountName: {{ include "keyrock.serviceAccountName" . }}
      {{- if .Values.theme.enabled }}
      initContainers:
        - name: {{ include "keyrock.fullname" . }}-theme-init
          image: {{ .Values.theme.image }}
          imagePullPolicy: {{ .Values.theme.imagePullPolicy }}
          volumeMounts:
            - name: themes-theme
              mountPath: {{ .Values.theme.sourceTheme }}
            - name: themes-img
              mountPath: {{ .Values.theme.sourceImg }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          {{- if .Values.theme.enabled }}
          volumeMounts:
            - name: themes-theme
              mountPath: {{ .Values.theme.mountTheme }}
            - name: themes-img
              mountPath: {{ .Values.theme.mountImg }}
          {{- end }}
          env:
            - name: IDM_PORT
              value: {{ .Values.port | quote }}
            - name: IDM_HOST
              value: {{ .Values.host }}
            - name: IDM_DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: IDM_DB_PASS
              valueFrom:
                 secretKeyRef:
                   name: {{ include "keyrock.fullname" . }}
                   key: dbPassword
            - name: IDM_DB_USER
              value: {{ .Values.db.user | quote }}
            {{- if .Values.admin }}
            - name: IDM_ADMIN_USER
              value: {{ .Values.admin.user | quote }}
            - name: IDM_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "keyrock.fullname" . }}
                  key: adminPassword
            - name: IDM_ADMIN_EMAIL
              value: {{ .Values.admin.email | quote }}
            {{- end }}
            #will be handled by the ingress
            - name: IDM_HTTPS_ENABLED
              value: "false"
            {{- if .Values.theme.enabled }}
            - name: IDM_THEME
              value: {{ .Values.theme.name | quote }}
            {{- end }}
            {{- with .Values.additionalEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.theme.enabled }}
      volumes:
        - name: themes-theme
          persistentVolumeClaim:
            claimName: {{ include "keyrock.fullname" . }}-themes-theme
        - name: themes-img
          persistentVolumeClaim:
            claimName: {{ include "keyrock.fullname" . }}-themes-img
      {{- end }}
