apiVersion: v1
kind: Service
metadata:
  name: {{ include "keyrock.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{ include "keyrock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "keyrock.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}