apiVersion: v1
name: canis-major
version: 0.1.4
appVersion: 1.5.15
description: A Helm chart for running canis major on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
  - fiware
  - canismajor
  - blockchain
  - dlt
sources:
  - https://github.com/FIWARE/CanisMajor
maintainers:
  - name: wistefan
    email: stefan.wiedemann@fiware.org
