apiVersion: v1
name: mintaka
version: 0.0.2
appVersion: 0.0.5
description: A Helm chart for running mintaka on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
- fiware
- orion
- orion-ld
- mintaka
sources:
- https://github.com/fiware/mintaka
maintainers:
- name: wistefan
  email: stefan.wiedemann@fiware.org