{{- if and .Values.bizEcosystemApis.enabled .Values.bizEcosystemApis.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bizEcosystemApis.serviceAccountName" . }}
{{- if .Values.bizEcosystemApis.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.bizEcosystemApis.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "bizEcosystemApis.labels" . | nindent 4 }}
{{- end }}
