apiVersion: v1
name: iotagent-json
version: 0.1.2
appVersion: 1.14.0
home: https://fiware-iotagent-json.readthedocs.io/en/latest/
description: A Helm chart for running the fiware iotagent-json on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
  - fiware
  - iot-agent
sources:
  - https://github.com/telefonicaid/iotagent-json
maintainers:
  - name: Sunny Malik
    email: t_sunny.malik@india.nec.com
