apiVersion: v1
name: vcverifier
version: 4.5.0
appVersion: 6.3.5
home: https://github.com/fiware/vcverifier
description: A Helm chart for running the FIWARE VCVerifier.
keywords:
  - FIWARE Data Space Connector
  - FIWARE
  - Verifiable Credentials
  - OID4VP
maintainers:
  - name: wistefan
    email: stefan.wiedemann@fiware.org
