{{- if .Values.ingress.httpNorth.enabled -}}
{{- $fullName := include "iota-ul.fullname" . -}}
{{- $httpNorthPort := .Values.service.httpNorthPort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "iota-ul.fullname" . }}-north
  labels:
    {{ include "iota-ul.labels" . | nindent 4 }}
  {{- if .Values.ingress.httpNorth.annotations }}
  annotations:
    {{- with .Values.ingress.httpNorth.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.httpNorth.tls }}
  tls:
    {{- range .Values.ingress.httpNorth.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.httpNorth.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $httpNorthPort }}
        {{- end }}
  {{- end }}
{{- end }}