apiVersion: v1
name: credentials-config-service
version: 2.4.4
appVersion: 3.3.5
description: A Helm chart for running the credentials-config-service on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
  - FIWARE
  - credentials-config-service
  - DSBA
  - VerifiableCredentials
  - IAM
sources:
  - https://github.com/fiware/credentials-config-service
maintainers:
  - name: wistefan
    email: stefan.wiedemann@fiware.org
