{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canis-major.fullname" . }}
  labels:
    {{ include "canis-major.labels" . | nindent 4 }}
type: Opaque
data:
  defaultAccount: {{ .Values.deployment.defaultAccount.privateKey | b64enc | quote }}
{{- end }}