apiVersion: v1
name: contract-management
version: 3.5.5
appVersion: 3.0.0
description: A Helm chart for running the contract-management on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
  - FIWARE
  - contract-management
  - DSBA
  - VerifiableCredentials
  - IAM
sources:
  - https://github.com/fiware/contract-management
maintainers:
  - name: pulledtim
    email: tim.smyth@fiware.org
