{{- if .Values.atContextServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.atContextServer.contextLabel }}
  name: {{ include "at-context-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.atContextServer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "at-context-server.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
  {{- with .Values.atContextServer.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        service: {{ include "at-context-server.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.atContextServer.image.repository }}:{{ .Values.atContextServer.image.tag }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.atContextServer.image.pullPolicy }}
        name: {{ include "at-context-server.fullname" . }}
        ports:
        - containerPort: 27015
          protocol: TCP
        {{- if .Values.atContextServer.readinessProbe.enabled }}
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT {{ .Values.atContextServer.eurekaAddress }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:27015/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.atContextServer.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.atContextServer.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.atContextServer.readinessProbe.periodSeconds }}
          {{- end}}
        {{- if .Values.atContextServer.livenessProbe.enabled }}  
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:27015/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.atContextServer.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.atContextServer.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.atContextServer.livenessProbe.periodSeconds }}
          {{- end }}

        resources:
{{ toYaml .Values.atContextServer.resources | indent 10 }}
      restartPolicy: {{ .Values.atContextServer.restartPolicy }}
      {{- if .Values.atContextServer.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.atContextServer.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.atContextServer.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.atContextServer.terminationGracePeriodSeconds }}
{{- end }}
