{{- if .Values.configServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.configServer.configLabel }}
  name: {{ include "config-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.configServer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "config-server.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
  {{- with .Values.configServer.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        service: {{ include "config-server.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.configServer.image.repository }}:{{ .Values.configServer.image.tag }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.configServer.image.pullPolicy }}
        name: {{ include "config-server.fullname" . }}
        ports:
        - containerPort: 8888
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT {{ .Values.configServer.eurekaAddress }}
        {{- if .Values.configServer.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:8888/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.configServer.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.configServer.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.configServer.readinessProbe.periodSeconds }}
          {{- end }}
        {{- if .Values.configServer.livenessProbe.enabled }}  
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:8888/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.configServer.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.configServer.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.configServer.livenessProbe.periodSeconds }}
          {{- end }}   
        resources:
{{ toYaml .Values.configServer.resources | indent 10 }}
      restartPolicy: {{ .Values.configServer.restartPolicy }}
      {{- if .Values.configServer.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.configServer.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.configServer.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.configServer.terminationGracePeriodSeconds }}
{{- end }}
