{{- if .Values.eureka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.eureka.eurekaLabel }}
  name: {{ include "eureka.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.eureka.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eureka.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
  {{- with .Values.eureka.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        service: {{ include "eureka.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.eureka.image.repository }}:{{ .Values.eureka.image.tag }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.eureka.image.pullPolicy }}
        name: {{ include "eureka.fullname" . }}
        ports:
        - containerPort: 8761
          protocol: TCP
        {{- if .Values.eureka.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:8761/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.eureka.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.eureka.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.eureka.readinessProbe.periodSeconds }}
          {{- end }}
        {{- if .Values.eureka.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:8761/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.eureka.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.eureka.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.eureka.livenessProbe.periodSeconds }}
          {{- end }}   
        resources:
{{ toYaml .Values.eureka.resources | indent 10 }}
      restartPolicy: {{ .Values.eureka.restartPolicy }}
      {{- if .Values.eureka.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.eureka.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.eureka.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.eureka.terminationGracePeriodSeconds }}
{{- end }}
