{{- if .Values.storageManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.storageManager.storageLabel }}
  name: {{ include "storage-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.storageManager.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "storage-manager.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
  {{- with .Values.storageManager.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        service: {{ include "storage-manager.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.storageManager.image.repository }}:{{ .Values.storageManager.image.tag }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.storageManager.image.pullPolicy }}
        name: {{ include "storage-manager.fullname" . }}
        ports:
        - containerPort: 1029
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT {{ .Values.storageManager.eurekaAddress }}
        {{- if .Values.storageManager.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1029/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.storageManager.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.storageManager.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.storageManager.readinessProbe.periodSeconds }}
          {{- end }}
        {{- if .Values.storageManager.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1029/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.storageManager.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.storageManager.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.storageManager.livenessProbe.periodSeconds }}
          {{- end }}  
        resources:
{{ toYaml .Values.storageManager.resources | indent 10 }}
      restartPolicy: {{ .Values.storageManager.restartPolicy }}
      {{- if .Values.storageManager.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.storageManager.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.storageManager.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.storageManager.terminationGracePeriodSeconds }}
{{- end }}
