apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dss.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dss.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
  {{- with .Values.deployment.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dss.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "dss.labels" . | nindent 8 }}
        {{- with .Values.deployment.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.deployment.additionalAnnotations -}}
      annotations:
        {{- with .Values.deployment.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec: 
      serviceAccountName: {{ include "dss.serviceAccountName" . }}
      {{- if .Values.deployment.initContainers }}
      initContainers:
        {{- with .Values.deployment.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          {{- if .Values.deployment.command }}
          command:
          {{- with .Values.deployment.command }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.deployment.args }}
          args: 
          {{- with .Values.deployment.args }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port}}
              protocol: TCP
            - name: http-health
              containerPort: {{ .Values.management.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          env:
            - name: MICRONAUT_SERVER_PORT
              value: {{ .Values.deployment.port | quote }}
            - name: ENDPOINTS_ALL_PORT
              value: {{ .Values.health.port | quote }}
            {{- if .Values.trust.enabled }}
            - name: MICRONAUT_CONFIG_FILES
              value: /trust-config/application.yaml
            {{- end }}
            {{- with .Values.additionalEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.trust.enabled }}
            - name: trust
              mountPath: /trust-config
            {{- end }}
            {{- if .Values.deployment.additionalVolumeMounts }}
            {{- with .Values.deployment.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      volumes:
        {{- if .Values.trust.enabled }}
        - name: trust
          configMap:
            name: {{ include "dss.fullname" . }}
        {{- end }}
        {{- if .Values.deployment.additionalVolumes }}
        {{- with .Values.deployment.additionalVolumes }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
        {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
